# Generated by Django 4.2.6 on 2023-10-28 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fname', models.CharField(default='', max_length=255)),
                ('lname', models.CharField(default='', max_length=255)),
                ('address', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=255)),
                ('password', models.TextField(default='')),
                ('contact', models.CharField(default='', max_length=20)),
                ('profile', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='SuperAdmin/')),
                ('Otp', models.IntegerField(default=0)),
                ('OtpCount', models.IntegerField(default=0)),
                ('OtpStatus', models.BooleanField(default=False)),
                ('no_of_attempts_allowed', models.IntegerField(default=3)),
                ('no_of_wrong_attempts', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('superadmin', 'superadmin'), ('manager', 'manager')], default='superadmin', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SVGModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('svg_file', models.FileField(upload_to='svg_files/')),
                ('svg_content', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='whitelistToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('token', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.superadmin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
